@startuml

class CargoPlane {
    List<Pallet> pallets
    List<Part> parts
}

class Pallet {
    List<Box> boxes
}

class Box {
    List<Item> items
}

class Part {
    String partNumber
}

class Item

CargoPlane "0..*" --> "0..*" Pallet : contains
Pallet "0..*" --> "0..*" Box : contains
CargoPlane "1..*" --> "1..*" Part : composedOf
Box "1" --> "0..*" Item : contains

@enduml
