@startuml

class CargoPlane {
    List<Pallet> pallets
    List<Part> parts
}

class Pallet {
    List<Box> boxes
}

class Box {
    List<Item> items
}

class Part

class Item
note Right of Item :Access by part number

CargoPlane "1" --o "0..*" Pallet : aggregation
Pallet "1" --o "0..*" Box : aggregation
CargoPlane "1" --* "1..*" Part : compose
Box "1" --* "1..*" Item : contains

@enduml
