@startuml

class University {
    List<Unit> units
}

class Unit {
    List<Faculty> faculties
    List<Student> students
    List<Staff> staffs
    AddressBook addressBook
}

class Faculty {
    List<Student> advisees
}

class Student

class Staff

class AddressBook {
    List<Entry> entries
}

class Entry {
    String lastName
    String universityId
}

University "1" --* "1..*" Unit : composed
Unit "1" --> "*" Faculty : contains
Unit "1" --> "*" Student : contains
Unit "1" --> "*" Staff : contains
Unit "1" --> "1" AddressBook : maintains
AddressBook "*" <--> "*" Entry
Entry "1" --> "*" Unit
Faculty "1" --> "0..*" Student : adviser

@enduml
