const ITEM_WIDTH = 100, IMAGE_HEIGHT = 100
const MILLISEC_TO_SEC = 1000
const MAP_HEIGHT = 11, MAP_WIDTH = 11
const FIRE_TIME = 0.8, BOMB_TIME = 3
const SPEED_UP_RATE = 0.2, BOMB_ADD_RATE = 0.3, FIREPLUS_RATE = 0.3
const SCALE_SIZE = 0.4

export { ITEM_WIDTH, IMAGE_HEIGHT, MILLISEC_TO_SEC, MAP_WIDTH, MAP_HEIGHT, FIRE_TIME, BOMB_TIME, SPEED_UP_RATE, BOMB_ADD_RATE, FIREPLUS_RATE, SCALE_SIZE }
