const ITEM_WIDTH = 100, IMAGE_HEIGHT = 100
const MILLISEC_TO_SEC = 1000
const MAP_HEIGHT = 11, MAP_WIDTH = 11
const FIRE_TIME = 1, BOMB_TIME = 3

export { ITEM_WIDTH, IMAGE_HEIGHT, MILLISEC_TO_SEC, MAP_WIDTH, MAP_HEIGHT, FIRE_TIME, BOMB_TIME }
